#!/usr/bin/env node
// Thin portable entrypoint to the installed ae-agent-lab demo-session workflow.
import { readFileSync, statSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const configPath = new URL("../local-runtime.json", import.meta.url);
let config;
try {
  config = JSON.parse(readFileSync(configPath, "utf8"));
} catch {
  console.error(
    "KYNEM is not installed yet: local-runtime.json must be generated by the installer.",
  );
  process.exit(1);
}
const [action, project, ...extra] = process.argv.slice(2);
if (
  extra.length ||
  !["info", "status", "start"].includes(action) ||
  (action !== "start" && project)
) {
  console.error("Usage: bridge.mjs info|status|start /absolute/project.aep");
  process.exit(2);
}
if (
  !isAbsolute(config.checkout || "") ||
  !isAbsolute(config.node || "") ||
  !isAbsolute(config.workflow || "") ||
  config.worker !== "ae-agent-lab-demo"
) {
  console.error("KYNEM installation config is incomplete or invalid. Re-run the installer.");
  process.exit(1);
}
if (action === "start" && (!project || !isAbsolute(project) || !/\.aep$/i.test(project))) {
  console.error("Provide the absolute path of the saved .aep to copy. No default demo is opened.");
  process.exit(2);
}
if (action === "info") {
  console.log(JSON.stringify(config, null, 2));
  process.exit(0);
}
try {
  if (action === "start" && !statSync(project).isFile()) throw new Error("Project is not a file.");
  const args = [resolve(config.checkout, "scripts/demo-session.mjs"), action];
  if (action === "start") args.push("--project", project);
  const result = spawnSync(config.node, args, { cwd: config.checkout, stdio: "inherit" });
  if (result.error) throw result.error;
  process.exit(result.status ?? 1);
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
